---
title: "ID variables"
author: "jmbadia"
date: "6/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
https://resources.github.com/whitepapers/github-and-rstudio/
### Project variables
* **projectName** = "Milk_stck2Addct_CONS": Name of the project. Usually a key word with some of the arguments used in it  
* **identDate** = "20200626_1905": Date and time the identification was made  
* **projectDirectory** = "invisible2Git/MS2ID_Identifications/20200608_Milk"  folder with all the project files  
* **mail2SendResult** = "josepmaria.badia@gmail.com": where the identification result has been send it  

  
### Consensus spectra variables

* **useCons** = TRUE: Binary indicating the use of consensus spectra. If FALSE (all or preselected) scans are identified individually
* **dec2binCons** = 2: last decimal to bin similar precursor mass. A 2 value means a 0.01 binning i.e. 78.04,78.05,78.06... Scans with mass precursor under the same bin are summarized on a unique consensus spectra  
* **mzdiff** = 0.02: Maximum allowed m/z difference among fragments (same spectra or not) in order to consider them as the same fragment  
* **minProp** = 2/3: Considering all the scans of a bin, minimum presence required for a fragment in order to be present in the consensus spectrum  
  
### Fragment bin & filter variables

* **dec2binFrag** = 2: Parameter to bin fragments (m/z) of two MS2 spectra before apply them a cosine similarity comparison technique. A 2 value means a 0.01 binning i.e. 78.04, 78.05, 78.06.....  
* **minNoiseAllowed** = 0.01: Minimum intensity value allowed (% relative to base peak) in the noise filtering of a spectra.  

### Identification variables

* **stck2Add** = TRUE: REF library subsetting argument. Boolean indicating if REF neutral mass must be compatible with UNK adducts (considering UNK precursor). We considere adducts the enviPat adducts list with UNK spectra polarization (positive or negative). NA's values are always non excluyent.  
* **samePrecMass** = FALSE: REF library subsetting argument. Boolean indicating if REF precursor mass and UNK precursor mass must be equals. NA's values are always non excluyent (default samePrecMass=FALSE).  
* **cosSimTh** = 0.8: cossine similarity threshold. REF spectra applicants with lower values than cosSimTh are eliminated (e.g. cosSimTh=0.9, default 0.8).  
* **massErrorTh** = 10: mass  ppm error contemplated on stick2Adducts and samePrecMass arguments (default massErrorAllowed=5 ppm).  
* **candNum** = 20: Lastly, number of best cossim REF spectra we keep (per UNK spectra) on the final result (default candidatesNumber=100).  
* **cl** = 2L: Processors to paralelize with the function. ONLY LINUX VERSION, otherwise, serial use (default value cl=NULL) should be used.
* **minCommMassNum** = 2: Filter by fragment argument. Resulting REF spectra must have at least a number N (minCommonMassNum value) of common fragments with UNK spectra (default minCommonMassNum=2).  
* **topMassNum** = 5: REF library subsetting argument. Only REF spectra with spectra whose top N (topMassesNum value) fragments share at list one mz with top N (topMassesNum value) UNK fragments (default, no subsetting).
* **REFfilt_db** = NULL: REF library subsetting argument. Vector with the db name we want to use as REF spectra library. (e.g. db=(db=c("metlin","nist")), default => no db restrictions).  


